apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iso-downloads-pvc
  labels:
    app: iso-downloader
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: ""