apiVersion: apps/v1
kind: Deployment
metadata:
  name: some-rabbit
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      hostname: my-rabbit
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: "user"
        - name: RABBITMQ_DEFAULT_PASS
          value: "password"
        ports:
        - containerPort: 5672
          name: amqp
        - containerPort: 15672
          name: management